Feature/components
Pyroarsonist/GoodsVille pull request #7
Opened 2019-11-10 23:26 UTC by valek2412

2019-11-11 09:59 UTC, Pyroarsonist requested changes

2019-11-11 09:59 UTC, Pyroarsonist commented on documentation/en.md
> +- Index for a certain lot.
что это за хуйня

2019-11-11 09:59 UTC, Pyroarsonist commented on documentation/en.md
> +- Index for a certain lot.
верни как было

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Categories/Categories.js
> +  const getCategory = [
семантика не соблюдена
`getCategory` - должна быть функцией, а не массивом
для массива лучшее название тут будет `categories`

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Categories/Categories.js
> +    <div className="">
убери пустой класснейм

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Room/AboutLot/index.js
> +import Link from '../../Link';
не используй релативные роуты

импортируй линк с `components/Link`

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Room/AboutLot/index.js
> +        {/* eslint-disable-next-line react/prop-types */}
я тут добавил дизейбл еслинта, убери это и добавь пропсы в проптайпы

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Room/AboutLot/index.js
> +        {/* eslint-disable-next-line react/prop-types */}
тут аналогично

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Room/AboutLot/index.js
> +  lot: PropTypes.shape({
у тебя тут был почему-то шелл, а не шейп и еслинт не сработал

 у тебя работают хуки гита?

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Room/index.js
> +    <>
фрагмент в главной компоненте рута это хуйня

добавивь див, по возможности с классом контейнера

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/Room/index.js
> +  id: PropTypes.number.isRequired,
не знаю, ругается ли в консоли или нет, но тут айдишник будет строкой

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/RoomList/Pagination/index.js
> +function Pagination() {
`Pagination` - это технология
назови `PaginationBlock`

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/RoomList/RoomItem/index.js
> +import Link from '../../Link';
линк

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/RoomList/index.js
> +  const getRooms = [
аналогично

2019-11-11 09:59 UTC, Pyroarsonist commented on src/components/RoomList/index.js
> +    <>
аналогично див

2019-11-12 19:56 UTC, valek2412 commented on documentation/en.md
> +- Index for a certain lot.
Оно автоматически поменяло, когда импорты правил xd

2019-11-12 20:04 UTC, valek2412 commented on src/components/RoomList/index.js
> +    <>
Бутстрап какого-то хера автоматически задает обычному диву класс контейнер с его отступами, которые там нахер не нужны. Пускай будет так

2019-11-17 22:52 UTC, Pyroarsonist approved these changes

2019-11-17 22:54 UTC, merged